api_platform:
    title: 'Truiter REST API'
    description: 'The Truiter API.'
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    formats:
        json:
            mime_types: [ 'application/json' ]
        html:
            mime_types: ['text/html']

    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header

    metadata_backward_compatibility_layer: false


